### ISSUE TITLE
Ubuntu 24.04 / gcc-13 Werror build fails in pvaClientChannel.cpp

### ISSUE THREAD

**Issue by ralphlange** [epics-base/pvaClientCPP#75]
In my fix-gha-config branch that bumps the Ubuntu builds to 22.04 / 24.04, the Werror build using Ubunto 24.04 / gcc-13 fails at a real warning in pvaClientChannel:

```c++
  ../pvaClientChannel.cpp: In member function ‘virtual void epics::pvaClient::PvaClientChannel::channelCreated(const epics::pvData::Status&, const epics::pvAccess::Channel::shared_pointer&)’:
  make[4]: Entering directory '/home/runner/work/epics-base/epics-base/modules/pvaClient/src/O.linux-x86_64'
  ../pvaClientChannel.cpp:182:59: error: ignoring return value of ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Allocator> std::operator+(__cxx11::basic_string<_CharT, _Traits, _Allocator>&&, const _CharT*) [with _CharT = char; _Traits = char_traits<char>; _Alloc = allocator<char>]’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
  g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE        -fdiagnostics-color -fdiagnostics-color -fstack-protector-strong -Wformat -Werror -Werror=format-security -Wno-error=deprecated-declarations -Wno-error=stringop-truncation -Wno-error=restrict -Wno-error=sizeof-pointer-memaccess -Wno-error=nonnull -Wno-error=dangling-pointer -Wno-error=format-overflow -Wno-error=stringop-overread -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -D_X86_64_ -DUNIX  -Dlinux      -O3 -g   -Wall     -std=c++20 -mtune=generic     -m64  -fPIC -I. -I../O.Common -I. -I. -I.. -I/home/runner/work/epics-base/epics-base/include/compiler/gcc -I/home/runner/work/epics-base/epics-base/include/os/Linux -I/home/runner/work/epics-base/epics-base/include -I/home/runner/work/epics-base/epics-base/include/compiler/gcc -I/home/runner/work/epics-base/epics-base/include/os/Linux -I/home/runner/work/epics-base/epics-base/include        -c ../pvaClientChannel.cpp
    182 |             + " status " +  status.getMessage() + " why??";
        |                                                           ^
  In file included from /usr/include/c++/13/string:54,
                   from /usr/include/c++/13/bits/locale_classes.h:40,
                   from /usr/include/c++/13/bits/ios_base.h:41,
                   from /usr/include/c++/13/ios:44,
                   from /usr/include/c++/13/ostream:40,
                   from /usr/include/c++/13/bits/unique_ptr.h:42,
                   from /usr/include/c++/13/memory:78,
                   from /home/runner/work/epics-base/epics-base/include/pv/event.h:12,
                   from ../pvaClientChannel.cpp:13:
  /usr/include/c++/13/bits/basic_string.h:3688:5: note: declared here
   3688 |     operator+(basic_string<_CharT, _Traits, _Alloc>&& __lhs,
        |     ^~~~~~~~
  cc1plus: all warnings being treated as errors
  make[4]: *** [/home/runner/work/epics-base/epics-base/configure/RULES_BUILD:268: pvaClientChannel.o] Error 1
```

https://github.com/ralphlange/epics-base/actions/runs/13394180716/job/37408907260#step:6:9599

Do you have an idea what's going wrong there? Some operator+() overloading magic fails.
To say it with the source code where the werror appears: "why??"

**Comment by mdavidsaver** [comment]
> Do you have an idea what's going wrong there? Some operator+() overloading magic fails.
> To say it with the source code where the werror appears: "why??"

I think the unary `+` is a distraction.

The warning/error comes from `operator+(const char*, std::string)`.  Since this allocates a new string, the method is apparently now decorated to warn if this newly allocated string is not stored.  Which here is the case...

The "must check" decoration didn't use to work for c++ types with a destructor, which I guess has changed with newer gcc.

**Comment by mdavidsaver** [comment]
Also, to state the possibly obvious.  Building strings with `operator+` is quite inefficient, and is seen as bad practice.  Use of `std::ostringstream` is preferred.

fyi. [a pattern](https://github.com/epics-base/pvxs/blob/f2e49a88445fd6f352cd7ec75d5c0f673756f43e/src/utilpvt.h#L78-L87) I have found myself using in all recent c++ project allows for lines like:

```c++
throw std::runtime_error(SB()<<'"'<<escape(ep)<<"\" comma expected before @");
```

**Comment by anjohnson** [comment]
@mdavidsaver Are you advocating trying to bring Marty's C++ code up to date? I believe this module is used a little, but I don't particularly want to encourage it. Efficiency doesn't seem important in code that may never have actually been called at all.

**Comment by sveseli** [comment]
PvaPy still uses it, so I am happy to see fixes like that.

**Comment by mdavidsaver** [comment]
> Are you advocating trying to bring Marty's C++ code up to date?

I am point out another example of what imo. are the endemic bad coding practices which led me to abandon my attempts to do just that.

**Comment by anjohnson** [comment]
Fixed by #76
